### ISSUE TITLE
Frontend) Missed URL on Company Logo Image

### ISSUE THREAD

**Issue by seonwoo0808** [VOAH-Platform/VOAH-Core#7]
<img width="236" alt="image" src="https://github.com/VOAH-Platform/VOAH-Core/assets/59224587/33eff038-cbe6-47f6-af4c-4739c3aae70a">

컴퍼니 이미지가 URL이 잘못 되어서 안 불러와 집니다...

`<img src="https://test-voah.zirr.al//api/company/image" class="c-bXpyeI">`
이 부분에 api앞에 "/"가 2개인데 1개로 변경해야 할 것 같아요

**Comment by tilto0822** [comment]
https://github.com/VOAH-Platform/VOAH-Core/commit/9c0be883bf3331955faaa319345df8a8b3e56fd5 커밋에서 해결되었습니다~
